### ISSUE TITLE
Error in one of the programs

### ISSUE THREAD

**Issue by TheGermanGuy** [fsmk/CS-VTU-Lab-Manual#131]
08_Zombie_process

#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
int main()
{
        int pid;
        if((pid=fork())<0)
                printf("fork error\n");
        else if(pid==0)
        {
                if((pid=fork())<0)
                        printf("fork error\n");
                else if(pid<0)  //should be replaced with "else if(pid>0)" <<<<<<<<<<<<<<<<<<<<<<<<<<<<
                        _exit(0);
                sleep(2);
                printf("second child,parent pid:%d\n",getppid());
                _exit(0);
        }
        _exit(0);
}

**Comment by KarthikNayak** [comment]
What's the error?

**Comment by viggyprabhu** [comment]
@KarthikNayak He must be mentioning about the missing include headers. @TheGermanGuy Where did you come across this error? Currently in the Markdown [here](https://github.com/fsmk/CS-VTU-Lab-Manual/blob/master/VTU/Sem6/USP_CD_Lab/08AvoidZombie/08_avoid_zombie.md), it seems ok? Did you get the issue in PDF?

**Comment by arunisaac** [comment]
@TheGermanGuy:
It's hard to read the code without indentation. Please indent your code. Use the code block or something.

Also, I rewrote this particular program in the latex branch. Please compare with that, and check if there is any bug in that program.

The code in the latex branch can be found at https://github.com/fsmk/CS-VTU-Lab-Manual/blob/latex/VTU/Sem6/USP_CD_Lab/08AvoidZombie/avoid_zombie.c

**Comment by dash-rai** [comment]
Lol, I know the code wasn't indented, but `else if(pid<0) //should be replaced with "else if(pid>0)" <<<<<<<<<<<<<<<<<<<<<<<<<<<<` should draw your attention.

**Comment by arunisaac** [comment]
Actually, the markdown code (in the master branch) is wrong for more than one reason. It doesn't even "ps" to show that there is no zombie process. Now I remember that's why I rewrote the program completely in the latex branch.

@dash-rai 
It's still good practice to indent the code! :-)

@TheGermanGuy 
I will copy the correct latex branch program to the master branch. With that, I suppose this issue will be resolved. Thanks for submitting the issue! Happy bug hunting!

**Comment by arunisaac** [comment]
I believe this issue is settled now.
