### ISSUE TITLE
Problem no 9 Wordlength is missing in new repo

### ISSUE THREAD

**Issue by shijiltv** [fsmk/CS-VTU-Lab-Manual#87]

**Comment by KarthikNayak** [comment]
@shijiltv update on the issue?

**Comment by cyberhck** [comment]
I didn't get the exact idea of this, I can find the wordlength program for first year in https://github.com/fsmk/CS-VTU-Lab-Manual/blob/master/VTU/Sem1_Sem2/OLD2010/CPP_Lab/08WordLength/08WordLength.md this url, it'd be better if we add proper file which is related and everything, I've no clue what this issue is all about.

**Comment by shijiltv** [comment]
I don't remember it now. I would suggest moderators to close this issue and proceed.
